# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: mailit
  pool: 5
  host: localhost
  username: mohammedsalim_ff
  password: salim@ff

#   adapter: postgresql
#   encoding: unicode
#   database: d1vmkfng94kqes
#   pool: 5
#   host: ec2-23-23-76-90.compute-1.amazonaws.com
#   username: jliepxybojzvgm
#   password: pkOYhuGCI8KBMS7lnPLTwfWG0T
